# Copyright 2019 Cohesity Inc.

#Nginx Servce
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 443
      protocol: TCP
      name: https
      cohesityPortTag: https-ui
      cohesityTag: ui
      cohesityEnv: INSIGHT_HTTPS_UI_PORT
---
#Nginx Pod Spec
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: grafana-nginx_server:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi 
---
# Graphana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-rest
  labels:
    app: grafana-ui
spec:
  type: ClusterIP
  selector:
    app: grafana-ui
  ports:
  - port: 3000
    protocol: TCP
    name: http
  securityContext:
    privileged: true
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana-ui
  labels:
    app: grafana-ui
spec:
  replicas:
    fixed: 1
  selector:
    matchLabels:
      app: grafana-ui
  template:
    metadata:
      labels:
        app: grafana-ui
    spec:
      containers:
      - name: grafana-ui
        image: grafana-custom
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
